# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ main ]
    
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Welcome Dear
        run: |
          echo "Let's start!"
          
      - name: show all working docker containers
        run: |
          docker ps -q
      
      - name: show all docker containers
        run: |
          docker ps -aq
      
      - name: stop and delete all docker containers
        run: |
          docker ps -aq | xargs --no-run-if-empty docker stop | xargs --no-run-if-empty docker rm
          
      - name: delete all created networks
        run: |
          docker network prune -f 
          
      #- name: delete all docker images
      #  run: |    
      #    docker rmi $(docker images -a -q)
          #docker rmi -f $(docker images -aq)
          
      #- name: stop and delete working docker containers only
      #  run: |
      #    docker ps -q | xargs docker stop | xargs docker rm
      
      - name: create all containers 
        run: |
          docker-compose -f "docker-compose.yml" up -d --build
