# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    #runs-on: ubuntu-latest
    runs-on: self-hosted
    
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Welcome Dear
        run: |
          echo "Let's start!"
          
      - name: show all working docker containers
        run: |
          docker ps -q
      
      - name: show all docker containers
        run: |
          docker ps -aq
      
      - name: stop and delete all docker containers
        run: |
          docker ps -aq | xargs --no-run-if-empty docker stop | xargs --no-run-if-empty docker rm
          
      - name: delete all created networks
        run: |
          docker network prune -f 
          
      #- name: delete all docker images
      #  run: |    
      #    docker rmi $(docker images -a -q)
          #docker rmi -f $(docker images -aq)
          
      #- name: stop and delete working docker containers only
      #  run: |
      #    docker ps -q | xargs docker stop | xargs docker rm
      
      - name: create all containers 
        run: |
          docker-compose -f "docker-compose.yml" up -d --build
